project:
  type: website

website:
  title: "Resume-and-info"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      

format:
  html:
    theme:
      light: journal
      dark: cyborg
    css: styles.css
    toc: true

editor: visual

