project:
  type: website
  output-dir: docs

website:
  title: "Resume-and-info"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      #- text: "Economics Papers"
       # menu:
          #- text: ""
          #  href: RCommands.html
          #- text: "R Markdown Hints"
          #  href: RMarkdownHints.html
          #- text: "R Cheatsheets & Notes"
          #  href: RCheatSheetsAndNotes.html
          #- text: "Data Sources"
          #  href: DataSources.html
      

format:
  html:
    theme:
      dark: cyborg
      light: journal
    css: styles.css
    toc: true

editor: visual

