---
title: "Resume"
format: 
  html: 
    page-layout: full
---

```{=html}
<style type="text/css">
.main-container {
  max-width: 90% !important;
  margin: auto;
}
</style>
```
```{=html}
<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
 
 function openTab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
 }    
</script>
```
# Tyson Brost

## Intro

I'm a Junior studying economics, and data science at BYU-Idaho. Former small business owner and operator, experienced in a wide variety of fields ranging from general construction to customer service and business management. I have a passion for analyzing systems and finding new ways to innovate in order to improve efficiency and effectiveness.

My schooling is focused on model interpretation and building, specifically in multivariate models, utilizing analysis and application of economic theory/policy as well as applied linear regression and econometrics.

[tyson.brost\@gmail.com](tyson.brost@gmail.com) [Linkedin](https://www.linkedin.com/in/tyson-brost-3604481b8) [Github](https://tbrost.github.io)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
library(pander)
```

## Education

| Degree                                | Year                  | Institution                      | Location       | Notes                                                           |
|---------------|---------------|---------------|---------------|---------------|
| Dual BS of Economics and Data Science | 2020-2024             | Brigham Young University - Idaho | Rexburg, Idaho | Minors in: Mathmatics, Statistics, Spanish                      |
| High-School                           | 2014-2018             | Washburn Rural                   | Topeka, Kansas |                                                                 |
| Masters / Doctorate                   | Anticipated 2025-2027 | TBD                              | TBD            | Seeking programs in Macro-economics and Developmental economics |

## Consulting

::: {#Consulting_Info .panel-tabset}
### **IWorQ**

#### Technical Project Manager - Remote

*Arranged through the Research and Business Development Center Based out of Rexburg, ID*

*April 2023 - Aug 2023*

Lead a small team of consultants and coordinated between the client and my team to ensure consistent communication and management of expectations and project scope throughout the duration of the project. Our task was to design and implement an automated analytics dashboard that would allow the client to better understand and react to their consumers activity and needs when using the software provided by the client. <a href="javascript:showhide('detailsIworq')"
style="font-size:.6em;">(More Details)</a>

::: {#detailsIworq style="display:none;"}
::: panel-tabset
## Data Loading and Cleaning

Developed a primary script in R which accessed the clients stored analytics data, cleaned, arranged, summarized and prepared it for analysis before storing it in the clients desired database system. Its primary abilities are as follows:

-   Accesses an Amazon S3 Bucket through Amazons API service.

-   Dynamically loads new files to local machine

-   Wrangles and cleans files using time stamp and function call data to calculate active user time and usage data metrics.

-   Saves resulting clean files as partitioned and compressed parquet files in an Amazon S3 server while preserving a local machine backup

## Analytics Application

Built a large scale Power-BI dashboard for SAAS data analytics, allowing the customer service and client leadership to quickly understand and learn the trends in usage and client activity for new and existing clients.

-   Worked extensively to coordinate expectations and results of graphical and tabular summaries between the client and my team to ensure both the clients outlined and underlying needs were met and exceeded when possible.

-   Developed secondary script in R that loads and aggregates a customizable range of historical cleaned data from the partitioned clean data stored in Amazon S3 into Power BI.

-   Lead project team through a change in the primary metric of measurement as the needs of the client became more apparent during the duration of our project

## Automation

Researched, tested and implemented fully automated systems provided by windows OS and the Microsoft Power Suite to schedule all scripts, datasets, reports, and dashboards to refresh weekly.
:::
:::

### **Westmark Credit Union**

#### Technical Project Consultant - Remote

*Arranged through the Research and Business Development Center Based out of Rexburg, ID*

*Jan 2023 - Apr 2023*

Worked as part of a small team to study and examine consumer data before building an interactive data exploration application embedded into a website for the client. <a href="javascript:showhide('detailsWestmark')"
style="font-size:.6em;">(More Details)</a>

::: {#detailsWestmark style="display:none;"}
::: panel-tabset
## Data Analysis

Worked with another project member to trial methods of trend and spike identification within consumer patterns.

## Application

Took primary dashboard built by the rest of the team and overhauled it by adding user interactive selection, searching, and filtering features before converting it into a web hosted report dashboard easily share-able and accessible to members within the clients organization.
:::
:::
:::

## Internships

::: {#Internships_Info .panel-tabset}
## Business

### **Advisors Excel**

#### Marketing Operations Intern - Topeka, KS

*April 2022 - Aug 2022*

Collaborated with a variety of teams and individuals across the marketing and IT departments on projects providing data and process insights and implementation strategies. <a href="javascript:showhide('detailsAE')"
style="font-size:.6em;">(More Details)</a>

::: {#detailsAE style="display:none;"}
::: panel-tabset
## Growth Solutions

Advised on future growth solutions as part of a Data Analytics and Management research team. This culminated in an eventual contract with one of the evaluated vendors.

-   Developed qualitative process to evaluate multiple costs and benefits of 3rd party SaaS and PaaS providers vs. internal development.

-   Met with and analyzed data situations and needs of each division of the marketing department

-   Aggregated and compared findings from interviews and pitches with companies and their abilities to meet the specific needs of each division at Advisors Excel (AE)

## Analytics Aggregation

Built Power-BI dashboards for website data analytics, creating an unprecedented view of aggregate and comparison level data across websites allowing for actionable analysis for the development team.

-   Researched and developed R-scripts to efficiently call and aggregate website traffic and interaction data using Google analytics API's for the 1800+ individual websites managed by AE.

-   Wrangled and formatted data within Power-BI to show actionable insights and trends based on individual, comparison, and aggregate site data.

## Website Migration

Lead a small sub-team as part of a larger effort to aggregate and reorganize over 15 separate corporate websites containing thousands of documents, multimedia, and blog posts into a collected whole.

-   Utilized excel and various WordPress plugins to automate significant portions of the project.
:::
:::

### **Hot Cup Factory**

###### Business Development Specialist - Rexburg, ID

*Sept 2021 - Jan 2022*

Worked closely with the company director to aggregate and collect data from across various departments within the company. While there I completed three major projects to help the company take advantage of a period of exponential growth during its first few years

::: panel-tabset
## Demand Analysis

Ongoing analysis of product demands for roughly 100 unique products with multiple suppliers in various countries within R. I further used a mixture of forecasting techniques to predict growth for the following year by product based on the company's and each product's growth patterns over the past 3 years. I then used these values to predict sales by month for each product within a dynamic Google sheets (preferred platform of company) allowing the company director to edit certain assumptions made within the calculations being made.

## Products

-   Creation of an additional dynamic dashboard using a variety of import methods and SQL queries within Google sheets to pull company inventory levels and predicted demands for each product from the aforementioned demand dashboard. This Order Dashboard allows viewing of monthly inventory levels based on current levels, any inbound items (in the process of shipping), as well as selectively estimate and include late products (old orders that haven't been shipped yet), as well as predicted orders and arrivals.
-   In-depth analysis of the target market, I then created a group of documents and tools for sales reps to utilize when working with customers to further up-sell and expose them to new products.
:::

### Research & Business Development Center

###### Research Analyst - Rexburg, ID

*July 2021 - Sep 2021*

Worked with a small team to analyze past data and results from previous studies to recreate and improve upon a generalized economic survey and study of Madison county in comparison to Idaho and Eastern Idaho.

This was used to help plan and promote specific industries within the area and identify sectors of economic leakages for Madison county Idaho.

## Statistics / Data Science / Quantitative Analysis

### Brigham Young University - Idaho

###### Research Assistant - Rexburg, ID

*Sep 2022 - Present*

Primary research assistant to Economics professor until graduation.

-   Working with professors to collect educational data through Canvas software API's

-   As data is collected we will begin using it to empirically analyze the effectiveness of various teaching methods and strategies in efforts to improve learning and teaching efficiency at various conceptual levels for students.

### Brigham Young University-Idaho

###### Mathematics/Economics Tutor - Rexburg, ID

*April 2021 - Current*

Work 1-on-1 with students or groups of students to help tutor and assist them in course work and understanding in a variety of introductory and upper-level college courses including;

-   Algebra

-   Introductory & Intermediate Statistics

-   Economic Statistics and Calculus

-   Econometrics

-   Financial Analytics

-   Macro & Micro Economics

Built a dynamic searching tool for tutor managers within Google sheets that utilizes query functions to import various spreadsheets and allow visualization of what times and days tutors are available by course.

Collaborated with other students to build Google app scripts to automate many traditionally manual tasks saving managers \~10 hours a week from time spent writing repetitive emails/texts.
:::

## Industry Experience

::: {#Experience .panel-tabset}
## Food Service

### The Happy Hut Shaved Ice

###### Owner - Topeka, KS

*March 2016 - August 2020*

-   Trained, managed, and coached new and existing employees in various positions

-   Created work schedules, menu creation, inventory management, and other operational duties

-   Analyzed marketing strategies, managed social media accounts, and created sales promotions

-   Grew sales by \~20% annually for over a period of four years, leading to gross revenue of over 35k in 2020

### ALDI

###### Stocking Associate - Topeka, KS

*May 2020 -- August 2020*

Worked early mornings with a small team and power jacks to stock and prepare the store for consumers as efficiently and effectively as possible.

### Hazel Hill Chocolates

###### Cashier/Closer - Topeka, KS

*December 2015 - May 2016*

-   Engaged customers to take, fulfill, and deliver requests with quality customer service and a friendly attitude

-   Cleaned, organized and stocked inventory, cleaned store, ran/counted register and locked-up.

## Construction

### Sunrise Homes

###### Framer - Rexburg, ID

*Sept 2020 - April 2021*

Performed general framing labor building residential homes in and around Rexburg, ID

### Top Knot Arborists

###### Arborist - St Louis, Mi

*July 2020 - Sept 2020*

Worked with a small team in St. Louis Missouri trimming, and removing large trees around residential buildings.

### Builder Bees LLC

###### General Construction - Topeka, KS

*May 2015 - September 2015*

Worked with a crew of \~10 building residential homes and decks.

Remodeled a large Business retreat complex now used by Advisors Excel.
:::

## Service History

### Service Missionary, Salt Lake City

*2018-2020*

Worked primarily with Spanish speaking immigrants;

-   Assisting with schooling

-   Work opportunities

-   General service

## Skills

-   Coding Languages; R, Python, PySpark, MySQL, DAX, M, Java
-   Power BI / RShiny / DataBricks
-   Google Sheets SQL Query

<!-- -->

-   Bi-lingual (Spanish)

-   Honesty

-   Dedicated Worker

-   Fast Learner

-   Ingenuity

-   Construction; Framing, Decks, Lawn Care/Groundskeeping,Tree trimming/felling

-   Digital Marketing/Social Media Management

### Certifications and Licences

-   Fundamentals Power BI - Microsoft

-   Spreadsheet Modeling - Harvard

-   Bloomberg Market Concepts
